tier = {
    "Fire Burst": .5,
    "Ice Storm": .5,
    "Thunder Rage": .5,
    "Shooting Star": .5,
    "POW Block": .5,
    "Shell Shock": .5,
    "Gold Bar": .5,
    "Gold Bar x3": .5,
    "Block Block": .5,
    "Volt Shroom": .5,
    "Ghost Shroom": .5,
    "Sleepy Sleep": .5,
    "Stop Watch": .5,
    "Shroom Shake": .5,
    "Super Shroom Shake": .5,
    "Ultra Shroom Shake": .5,
    "Dried Shroom": .5,
    "Life Shroom": .5,
    "Long-Last Shake": .5,
    "Blue Apple": .5,
    "Yellow Apple": .5,
    "Red Apple": .5,
    "Pink Apple": .5,
    "Black Apple": .5,
    "Poison Shroom": .5,
    "Slimy Shroom": .5,
    "Peachy Peach": .5,
    "Keel Mango": .5,
    "Primordial Fruit": .5,
    "Golden Leaf": .5,
    "Turtley Leaf": .5,
    "Cake Mix": .5,
    "Whacka Bump": .5,
    "Horsetail": .5,
    "Fresh Pasta Bunch": .5,
    "Hot Sauce": .5,
    "Inky Sauce": .5,
    "Dayzee Tear": .5,
    "Sap Soup": .5,
    "Bone-In Cut": .5,
    "Fresh Veggie": .5,
    "Smelly Herb": .5,
    "Honey Jar": .5,
    "Power Steak": .5,
    "Big Egg": .5,
    "Mild Cocoa Bean": .5,
    'Block Meal': 1,
    'Courage Shell': 1,
    'Dangerous Delight': 1,
    'Dayzee Syrup': 1,
    'Electro Pop': 1,
    'Fried Egg': 1,
    'Fried Shroom Plate': 1,
    'Golden Meal': 1,
    'Hamburger': 1,
    'Healthy Salad': 1,
    'Herb Tea': 1,
    'Honey Candy': 1,
    'Inky Soup': 1,
    'Koopa Tea': 1,
    'Mango Juice': 1,
    'Megaton Dinner': 1,
    'Meteor Meal': 1,
    'Mistake (Sleepy Sheep)': 1,
    'Peach Juice': 1,
    'Roast Horsetail': 1,
    'Roast Shroom Dish': 1,
    'Roast Whacka Bump': 1,
    'Sap Syrup': 1,
    'Shroom Steak': 1,
    'Sky Juice': 1,
    'Slimy Extract': 1,
    'Snow Cone': 1,
    'Spaghetti Plate': 1,
    'Spicy Soup': 1,
    'Spit Roast': 1,
    'Sweet Cookie Snack': 1,
    'Town Special': 1,
    'Warm Cocoa': 1,
    'Awesome Snack': 2,
    'Choco Pasta Dish': 2,
    'Chocolate Cake': 2,
    'Egg Bomb': 2,
    'Emergency Ration': 2,
    'Fruity Cake': 2,
    'Fruity Hamburger': 2,
    'Fruity Punch': 2,
    'Fruity Shroom': 2,
    'Golden Choco-bar': 2,
    'Gorgeous Steak': 2,
    'Gradual Syrup': 2,
    'Heavy Meal': 2,
    'Honey Shroom': 2,
    'Honey Super': 2,
    'Horsetail Tart': 2,
    'Hot Dog': 2,
    'Ink Pasta Dish': 2,
    'Koopa Dumpling': 2,
    'Koopa Pilaf': 2,
    'Koopasta Dish': 2,
    'Love Pudding': 2,
    'Lovely Chocolate': 2,
    'Mango Pudding': 2,
    'Meat Pasta Dish': 2,
    'Mousse': 2,
    'Mushroom Crepe': 2,
    'Omelette Plate': 2,
    'Peach Tart': 2,
    'Primordial Dinner': 2,
    'Sap Muffin': 2,
    'Shroom Broth': 2,
    'Shroom Cake': 2,
    'Shroom Choco-bar': 2,
    'Snow Bunny': 2,
    'Space Food': 2,
    'Spicy Dinner': 2,
    'Spicy Pasta Dish': 2,
    'Stamina Juice': 2,
    'Standard Chocolate': 2,
    'Sweet Choco-bar': 2,
    'Volcano Shroom': 2,
    'Weird Extract': 2,
    'Dyllis Breakfast': 3,
    'Dyllis Dinner': 3,
    'Dyllis Lunch': 3,
    'Fruit Parfait': 3,
    'Heartful Cake': 3,
    'Love Noodle Dish': 3,
    'Odd Dinner': 3,
    'Veggie Set': 3,
    'Dyllis Deluxe': 4,
    'Dyllis Special': 4,
    'Mixed Shake': 4,
    'Berry Snow Bunny': 5,
    'Shroom Delicacy': 5,
    'Shroom Pudding': 5,
    "Couple's Cake": 6,
    'Dyllis Dynamite': 6,
    'Gingerbread House': 6,
    'Luxurious Set': 6, 
    'Trial Stew': 1
}